/*
 Copyright (c) 2003-2018, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.dialog.add("mathlive",function(d){function h(a){f&&(CKEDITOR.plugins.mathlive.addCssLink(CKEDITOR.document,d.config.katexCss),f.setHtml(CKEDITOR.tools.htmlEncode(CKEDITOR.plugins.mathlive.wrapMath(a,d))),CKEDITOR.plugins.mathlive.loadKatex(d,function(b){if(b&&window.katex){b=CKEDITOR.plugins.mathlive.stripDelimiters(CKEDITOR.plugins.mathlive.wrapMath(a,d));try{f.setHtml(window.katex.renderToString(b.latex,{displayMode:b.display,throwOnError:!1}))}catch(e){f.setHtml(CKEDITOR.tools.htmlEncode(a))}}}))}
function k(){var a=e?e.getValue():"";c||(c=!0,b&&b.value!=a&&(b.value=a),c=!1,h(a))}function n(){!c&&b&&(c=!0,e&&e.setValue(b.value),c=!1,h(b.value))}function p(){var a;if(!b&&l&&window.customElements&&window.customElements.get("math-field")){var d=CKEDITOR.document;if(!d.getById("cke_mathlive_keyboard_style")){var c=d.createElement("style");c.setAttributes({id:"cke_mathlive_keyboard_style"});c.setHtml(":root { --keyboard-zindex: 20000; }");c.appendTo(d.getHead())}a=CKEDITOR.document.$.createElement("math-field");
a.style.width="100%";a.style.minHeight="48px";a.style.fontSize="20px";a.setAttribute("virtual-keyboard-mode","auto");a.setAttribute("math-virtual-keyboard-policy","auto");a.value=e?e.getValue():"";a.addEventListener("input",n);a.addEventListener("focusin",function(){window.mathVirtualKeyboard&&window.mathVirtualKeyboard.show()});l.$.appendChild(a);b=a;setTimeout(function(){a.focus()},100)}}function m(){CKEDITOR.plugins.mathlive.loadMathLive(d,function(a){a&&p()})}var g=d.lang.mathlive,b,e,f,l,c=!1;
return{title:g.title,minWidth:500,minHeight:300,onShow:function(){m();k();b&&setTimeout(function(){b.focus()},100)},onHide:function(){window.mathVirtualKeyboard&&window.mathVirtualKeyboard.hide()},contents:[{id:"info",elements:[{id:"mathfield",type:"html",html:'\x3cdiv class\x3d"cke_mathlive_host" style\x3d"width:100%;min-height:54px;margin-bottom:8px"\x3e\x3c/div\x3e',onLoad:function(){l=CKEDITOR.document.getById(this.domId).getChild(0);m()}},{id:"equation",type:"textarea",rows:7,label:g.dialogInput,
onLoad:function(){e=this;this.getInputElement().on("keyup",k);this.getInputElement().on("change",k)},setup:function(a){a=CKEDITOR.plugins.mathlive.stripDelimiters(a.data.math).latex;this.setValue(a);b&&(b.value=a);h(a)},commit:function(a){var c=b?b.value:this.getValue();a.setData("math",CKEDITOR.plugins.mathlive.wrapMath(c,d))}},{id:"documentation",type:"html",html:'\x3cdiv style\x3d"width:100%;text-align:right;margin:-8px 0 10px"\x3e\x3ca class\x3d"cke_mathlive_doc" href\x3d"'+g.docUrl+'" target\x3d"_blank" style\x3d"cursor:pointer;color:#00B2CE;text-decoration:underline"\x3e'+
g.docLabel+"\x3c/a\x3e\x3c/div\x3e"},{id:"preview",type:"html",html:'\x3cdiv class\x3d"cke_mathlive_preview" style\x3d"width:100%;min-height:36px;text-align:center;font-size:20px"\x3e\x3c/div\x3e',onLoad:function(){f=CKEDITOR.document.getById(this.domId).getChild(0)}}]}]}});