/*
 Copyright (c) 2003-2018, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
(function(){function p(b,d){var a=b&&b.parent,e=a&&a.attributes&&a.attributes["class"];return a&&"span"==a.name&&e&&-1<(" "+e+" ").indexOf(" "+d+" ")}function q(b){b=b.parent&&CKEDITOR.dtd[b.parent.name];return!b||b.span}function n(b){b=CKEDITOR.tools.trim(String(b||""));return 0===b.indexOf("\\(")&&"\\)"==b.substr(b.length-2)||0===b.indexOf("\\[")&&"\\]"==b.substr(b.length-2)||0===b.indexOf("$$")&&"$$"==b.substr(b.length-2)?{latex:b.substring(2,b.length-2)}:"$"==b.charAt(0)&&"$"==b.charAt(b.length-
1)?{latex:b.substring(1,b.length-1)}:{latex:b}}function g(b,d){var a=0;for(d--;0<=d&&"\\"==b.charAt(d);)a++,d--;return 1==a%2}function k(b,d,a,e){for(var c;d<=b.length-a.length;d++){c=b.charAt(d);if(!e&&("\n"==c||"\r"==c))break;if(b.substr(d,a.length)==a&&!g(b,d)&&("$"!=a||"$"!=b.charAt(d-1)&&"$"!=b.charAt(d+1)))return d}return-1}function m(b,d,a,e,c){e+=c;d=d.substring(a,e);a:if(c=CKEDITOR.tools.trim(n(d).latex)){if("$"==d.charAt(0)&&"$$"!=d.substr(0,2)){var f=n(d).latex;if(f!==CKEDITOR.tools.trim(f)||
/^[\d\s.,]+$/.test(c)){c=!1;break a}}c=!0}else c=!1;return c?(b.push({start:a,end:e,value:d}),e):a+1}function r(b,d){var a,e=[],c=0,f;for(a=String(b||"");c<a.length;){if("\\("==a.substr(c,2)&&!g(a,c)&&(f=k(a,c+2,"\\)",!0),-1<f)){c=m(e,a,c,f,2);continue}if("\\["==a.substr(c,2)&&!g(a,c)&&(f=k(a,c+2,"\\]",!0),-1<f)){c=m(e,a,c,f,2);continue}if("$$"==a.substr(c,2)&&!g(a,c)&&(f=k(a,c+2,"$$",!0),-1<f)){c=m(e,a,c,f,2);continue}if("$"==a.charAt(c)&&"$"!=a.charAt(c-1)&&"$"!=a.charAt(c+1)&&!g(a,c)&&(f=k(a,c+
1,"$",!1),-1<f)){c=m(e,a,c,f,1);continue}c++}a="";var c=0,h;for(f=0;f<e.length;f++)h=e[f],a+=b.substring(c,h.start),a+=d(h.value,h),c=h.end;return a+b.substring(c)}CKEDITOR.plugins.add("mathjax",{lang:"en",requires:"widget,dialog",icons:"mathjax",hidpi:!0,init:function(b){var d=b.config.mathJaxClass||"math-tex";b.config.mathJaxLib||(b.config.mathJaxLib="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config\x3dTeX-AMS-MML_HTMLorMML");b.widgets.add("mathjax",{inline:!0,dialog:"mathjax",
button:b.lang.mathjax.button,mask:!0,allowedContent:"span(!"+d+")",styleToAllowedContentRules:function(a){a=a.getClassesArray();if(!a)return null;a.push("!"+d);return"span("+a.join(",")+")"},pathName:b.lang.mathjax.pathName,template:'\x3cspan class\x3d"'+d+'" style\x3d"display:inline-block" data-cke-survive\x3d1\x3e\x3c/span\x3e',parts:{span:"span"},defaults:{math:"$x,y$"},init:function(){var a=this.parts.span.getChild(0);a&&a.type==CKEDITOR.NODE_ELEMENT&&a.is("iframe")||(a=new CKEDITOR.dom.element("iframe"),
a.setAttributes({style:"border:0;width:0;height:0",scrolling:"no",frameborder:0,allowTransparency:!0,src:CKEDITOR.plugins.mathjax.fixSrc}),this.parts.span.append(a));this.once("ready",function(){CKEDITOR.env.ie&&a.setAttribute("src",CKEDITOR.plugins.mathjax.fixSrc);this.frameWrapper=new CKEDITOR.plugins.mathjax.frameWrapper(a,b);this.frameWrapper.setValue(this.data.math)})},data:function(){this.frameWrapper&&this.frameWrapper.setValue(this.data.math)},upcast:function(a,b){if("span"==a.name&&a.hasClass(d)&&
!(1<a.children.length||a.children[0].type!=CKEDITOR.NODE_TEXT)){b.math=CKEDITOR.tools.htmlDecode(a.children[0].value);var c=a.attributes;c.style=c.style?c.style+";display:inline-block":"display:inline-block";c["data-cke-survive"]=1;a.children[0].remove();return a}},downcast:function(a){a.children[0].replaceWith(new CKEDITOR.htmlParser.text(CKEDITOR.tools.htmlEncode(this.data.math)));var b=a.attributes;b.style=b.style.replace(/display:\s?inline-block;?\s?/,"");""===b.style&&delete b.style;return a}});
CKEDITOR.dialog.add("mathjax",this.path+"dialogs/mathjax.js");b.on("contentPreview",function(a){a.data.dataValue=a.data.dataValue.replace(/<\/head>/,'\x3cscript   src\x3d"'+CKEDITOR.getUrl(b.config.mathJaxLib)+'"\x3e\x3c/script\x3e\x3c/head\x3e')});b.on("paste",function(a){a.data.dataValue=a.data.dataValue.replace(new RegExp("\x3cspan[^\x3e]*?"+d+".*?\x3c/span\x3e","ig"),function(a){return a.replace(/(<iframe.*?\/iframe>)/i,"")})})},afterInit:function(b){b.dataProcessor.dataFilter.addRules({text:function(d,
a){var e=b.config.mathJaxClass||"math-tex";if(q(a)&&!p(a,e))return r(d,function(a){var d=new CKEDITOR.htmlParser.element("span",{"class":e});a="$"+n(a).latex+"$";d.add(new CKEDITOR.htmlParser.text(a));return b.widgets.wrapElement(d,"mathjax").getOuterHtml()})}})}});CKEDITOR.plugins.mathjax={};CKEDITOR.plugins.mathjax.fixSrc=CKEDITOR.env.gecko?"javascript:true":CKEDITOR.env.ie?"javascript:void((function(){"+encodeURIComponent("document.open();("+CKEDITOR.tools.fixDomain+")();document.close();")+"})())":
"javascript:void(0)";CKEDITOR.plugins.mathjax.loadingIcon=CKEDITOR.plugins.get("mathjax").path+"images/loader.gif";CKEDITOR.plugins.mathjax.copyStyles=function(b,d){for(var a="color font-family font-style font-weight font-variant font-size".split(" "),e=0;e<a.length;e++){var c=a[e],f=b.getComputedStyle(c);f&&d.setStyle(c,f)}};CKEDITOR.plugins.mathjax.trim=function(b){var d=b.indexOf("$")+1,a=b.lastIndexOf("$");d<a&&(b=b.substring(d,a));return b};CKEDITOR.plugins.mathjax.frameWrapper=CKEDITOR.env.ie&&
8==CKEDITOR.env.version?function(b,d){b.getFrameDocument().write('\x3c!DOCTYPE html\x3e\x3chtml\x3e\x3chead\x3e\x3cmeta charset\x3d"utf-8"\x3e\x3c/head\x3e\x3cbody style\x3d"padding:0;margin:0;background:transparent;overflow:hidden"\x3e\x3cspan style\x3d"white-space:nowrap;" id\x3d"tex"\x3e\x3c/span\x3e\x3c/body\x3e\x3c/html\x3e');return{setValue:function(a){var e=b.getFrameDocument(),c=e.getById("tex");c.setHtml(CKEDITOR.plugins.mathjax.trim(CKEDITOR.tools.htmlEncode(a)));CKEDITOR.plugins.mathjax.copyStyles(b,
c);d.fire("lockSnapshot");b.setStyles({width:Math.min(250,c.$.offsetWidth)+"px",height:e.$.body.offsetHeight+"px",display:"inline","vertical-align":"middle"});d.fire("unlockSnapshot")}}}:function(b,d){function a(){l=b.getFrameDocument();l.getById("preview")||(CKEDITOR.env.ie&&b.removeAttribute("src"),l.write("\x3c!DOCTYPE html\x3e\x3chtml\x3e\x3chead\x3e\x3cmeta charset\x3d\"utf-8\"\x3e\x3cscript type\x3d\"text/x-mathjax-config\"\x3eMathJax.Hub.Config({\ttex2jax: {\t  inlineMath: [ ['$','$'],['\\[','\\]'] ,['\\(','\\)'] ]\t},  messageStyle: \"none\"  });function getCKE() {if ( typeof window.parent.CKEDITOR \x3d\x3d 'object' ) {return window.parent.CKEDITOR;} else {return window.parent.parent.CKEDITOR;}}function update() {MathJax.Hub.Queue([ 'Typeset', MathJax.Hub, this.buffer ],function() {getCKE().tools.callFunction( "+
p+" );});}MathJax.Hub.Queue( function() {getCKE().tools.callFunction("+n+');} );\x3c/script\x3e\x3cscript src\x3d"'+d.config.mathJaxLib+'"\x3e\x3c/script\x3e\x3c/head\x3e\x3cbody style\x3d"padding:0;margin:0;background:transparent;overflow:hidden"\x3e\x3cspan id\x3d"preview"\x3e\x3c/span\x3e\x3cspan id\x3d"buffer" style\x3d"display:none"\x3e\x3c/span\x3e\x3c/body\x3e\x3c/html\x3e'))}function e(){m=!0;h=g;d.fire("lockSnapshot");c.setHtml(h);f.setHtml("\x3cimg src\x3d"+CKEDITOR.plugins.mathjax.loadingIcon+
" alt\x3d"+d.lang.mathjax.loading+"\x3e");b.setStyles({height:"16px",width:"16px",display:"inline","vertical-align":"middle"});d.fire("unlockSnapshot");l.getWindow().$.update(h)}var c,f,h,g,l=b.getFrameDocument(),k=!1,m=!1,n=CKEDITOR.tools.addFunction(function(){f=l.getById("preview");c=l.getById("buffer");k=!0;g&&e();CKEDITOR.fire("mathJaxLoaded",b)}),p=CKEDITOR.tools.addFunction(function(){CKEDITOR.plugins.mathjax.copyStyles(b,f);f.setHtml(c.getHtml());d.fire("lockSnapshot");b.setStyles({height:0,
width:0});var a=Math.max(l.$.body.offsetHeight,l.$.documentElement.offsetHeight),k=Math.max(f.$.offsetWidth,l.$.body.scrollWidth);b.setStyles({height:a+"px",width:k+"px"});d.fire("unlockSnapshot");CKEDITOR.fire("mathJaxUpdateDone",b);h!=g?e():m=!1});b.on("load",a);a();return{setValue:function(a){g=CKEDITOR.tools.htmlEncode(a);k&&!m&&e()}}}})();